apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-feature-x
spec:
  hosts:
  - 'feature-x.redhat-kubecon.io'
  gateways:
  - customer-gateway
  http:
  - match:
    - uri:
        exact: /kubecon/
    rewrite:
      uri: /
    route:
    - destination:
        host: customer
        subset: v1
        port:
          number: 8080
    headers:
      request:
        add:
          x-test-suite: feature-x
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer-feature-y
spec:
  hosts:
  - 'feature-y.redhat-kubecon.io'
  gateways:
  - customer-gateway
  http:
  - match:
    - uri:
        exact: /kubecon/
    rewrite:
      uri: /
    route:
    - destination:
        host: customer
        subset: v1
        port:
          number: 8080
    headers:
      request:
        add:
          x-test-suite: feature-y