name: Build Customer

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'workshop/content/src/customer/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn clean package --file workshop/content/src/customer/ -DskipTests
    - name: Build the Docker image
      working-directory: workshop/content/src/customer
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKER_USERNAME }}/lab-ossm-customer:${{ github.sha }}
        docker push docker.io/${{ secrets.DOCKER_USERNAME }}/lab-ossm-customer:${{ github.sha }}
    - name: Deploy preview
      uses: maistra/istio-workspace-action@master
      with:
        action: create
        server: ${{ secrets.K8S_API_SERVER }}
        token: ${{ secrets.K8S_TOKEN }}
        session: ${{ github.head_ref }}
        namespace: ${{ secrets.DEMO_NS }}
        deployment: customer-v1
        route: header:ike-session-id=${{ github.head_ref }}
        image: docker.io/${{ secrets.DOCKER_USERNAME }}/lab-ossm-customer:${{ github.sha }}