name: Build Recommendation

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn clean package --file workshop/content/src/recommendation/ -DskipTests
    - name: Build the Docker image
      working-directory: workshop/content/src/recommendation
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build . --file Dockerfile --tag docker.io/aslakknutsen/lab-ossm-recommendation:${{ github.sha }}
        docker push docker.io/aslakknutsen/lab-ossm-recommendation:${{ github.sha }}
    - name: Deploy preview
      uses: maistra/istio-workspace-action@master
      with:
        action: create
        server: ${{ secrets.K8S_API_SERVER }}
        token: ${{ secrets.K8S_TOKEN }}
        session: ${{ github.head_ref }}
        namespace: 
        deployment: recommendation-v1
        route: header:ike-session-id=${{ github.head_ref }}
        image: docker.io/aslakknutsen/lab-ossm-recommendation:${{ github.sha }}